### PR TITLE
Added basic readthedocs framework

### PR DESCRIPTION
**Pull request by decarlof**
Now readthedocs pages are automatically generated at http://timbir.readthedocs.org
To do:
add data collection pyEpics scripts from the APS
move the example in the docs
add/improve documentation in the C/C++ code
rename Source_Code in src
...

### CODE REVIEW

**Comment by adityamnk** [comment]
I have merged the changes. Please check! Let me know if you notice any issues. Thanks a lot!

**Comment by decarlof** [comment]
Aditya, I am not sure how you did the merge. I see the pull request is closed (not merged) and my fork still parallel to yours

**Comment by adityamnk** [comment]
Hi Francesco,
Thanks! Let me check it out. There was a conflict and I merged the changes to the master from command line. I could revert and then retry. 
Thanks
Aditya
On Mar 15, 2016 6:48 PM, Francesco De Carlo notifications@github.com wrote:Aditya, I am not sure how you did the merge. I see the pull request is closed (not merged) and my fork still parallel to yours

**Comment by decarlof** [comment]
yes I see it now the possible conflict is a name change I propose for the source code directory to src and the fact that you touched one file (uncommented  -#MACROS = -DNO_COST_CALCULATE -DNO_DEBUG #Macros) and delete another in that directory.

The github merge it should be straight forward but if you are not familiar is  faster to revert to bd69e76df9bd92d93a9f761685b9c89d4a656a7f then I will create a new pull request that will merge 
with no conflicts that delete your file and uncomment -#MACROS = -DNO_COST_CALCULATE -DNO_DEBUG #Macros again.

**Pull request closed without merging**
